### ISSUE TITLE
Tests failed due to an error of JARM verification since conformance suite version 5.1.8

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#455]
### Describe the bug

Since the conformance suite version 5.1.8, all conformance tests including JARM verification fail.

### Version

conformance suite version 5.1.8 or later

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/504
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/505
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/506
```
