### ISSUE TITLE
Make sure this test environment supports a conformance test requiring DPoP

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#615]
### Description

The current test environment does not support running a conformance test requiring DPoP.
The reason was described by comments in https://github.com/keycloak/keycloak/issues/31970 .

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/640
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/642
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/653
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/658
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/656
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/668
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/666
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/664
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/662
- [ ] https://github.com/keycloak/kc-sig-fapi/issues/660
```
